fakecsi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('register/',views.NewqView.as_view(), name='addquestion'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/posts/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/likes/', views.vote, name='vote'),
    path('newq/success/', views.newq, name='newq'),
    path('<int:pk>/newpost/', views.NewcView.as_view(), name='addchoice'),
    path('<int:question_id>/newpost/add',views.newc, name='newc'),
    path("<int:question_id>/delete/", views.delete, name="delete")
    ]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('question_text')

class NewqView(generic.ListView):
    model = Question
    template_name = 'polls/newq.html'

class NewcView(generic.DetailView):
    model = Question
    template_name = 'polls/newc.html'

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def newq(request):
    new_question = Question(question_text = request.POST['newquestion'], pub_date=timezone.now())
    new_question.save()
    return HttpResponseRedirect(reverse('polls:index', args=''))

def newc(request, question_id):
    question = Question.objects.get(id=question_id)
    new_choice = question.choice_set.create(choice_text=request.POST['newchoice'])
    new_choice.save()
    return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select anything.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        
def delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['delete'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select anything.",
        })
    else:
        selected_choice.delete()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))

polls/templates/polls/detail.html
<head>
    <title>{{ question.question_text }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.0/css/all.css" rel="stylesheet">
</head>

<body style="background-color: powderblue;">
    <div class="container">
        <div class="jumbotron">    
    
            <h1 style="font-family: papyrus">{{ question.question_text }}</h1>
            <p style="font-family: papyrus">Posts</p>
        </div>
    </div>

    <div class="container">
        <div class="pl-1" style="width: 500px;">
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}


            {% if question.choice_set.all %}
                {% for choice in question.choice_set.all %}
                    
                        <div class="pl-2">
                            <div class="container">
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            {{ choice.choice_text }}
                                        </div>

                                        <div class="col-sm-1">
                                            <form action="{% url 'polls:vote' question.id %}" = method="post">    
                                                {% csrf_token %}
                                                <button class="btn btn-primary" type="submit" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" >
                                                    <i class="far fa-thumbs-up"></i>  
                                                </button>
                                            </form>
                                        </div>
                                        <div class="col-sm-1">
                                            <form action="{% url 'polls:delete' question.id %}" method="post">
                                                {% csrf_token %}
                                                <button class="btn btn-danger" type="submit" name="delete" id="choice{{ forloop.counter }}" value="{{ choice.id }}" >
                                                    <i class="far fa-trash-alt"></i>
                                                </button>

                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                {% endfor %}
            {% else %}
                <p>No posts yet :(</p>
            {% endif %}

        </div>
    </div>

    <div class="container">
        <form action="{% url 'polls:addchoice' question.id %}">
            <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-pencil-alt"></i>  Create New Post</button> 
        </form>

        <form action="{% url 'polls:index' %}">
            <button type="submit" class="btn btn-info btn-block"><i class="fas fa-home"></i>  Back to Home</button>
        </form>
    </div>
</body>

polls/templates/polls/index.html
<head>
    <title>Good Forum</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.0/css/all.css" rel="stylesheet">
</head>
<body style="background-color: powderblue;">

    <div class='container'>
        <div class='jumbotron'>
            <h1 style="font-family:papyrus;">Welcome to Good Forum!</h1>
            <p style="font-family:papyrus;"> Give yourself a name and write about anything you want!</p>
        </div>
    </div>

    <form action="{% url 'polls:addquestion' %}">
        <div class='container'> 
        
            {% if latest_question_list %}
        
                {% for question in latest_question_list %}
                    <div class="form-group">
                        <div class="row" align="left">
                            <div class="pl-3" style="width: 250px;">
                                <a href="{% url 'polls:detail' question.id %}" class="form-control">{{ question.question_text }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                    
            {% else %}
                <p>No people yet :(</p>
            {% endif %}         
        </div>

        <div class="container">
            <button type="submit" class="btn btn-primary btn-large btn-block"><i class="fas fa-users" aria-hidden="true"></i>  Create New Account</button>
        </div>
    </form>
</body>

polls/templates/polls/newc.html
<head>
    <title>Say Something!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link href="https://use.fontawesome.com/releases/v5.0.0/css/all.css" rel="stylesheet">
</head>
<body style="background-color: powderblue;">
<div class="container">
    <div class="jumbotron">    

        <h1 style="font-family: papyrus">{{ question.question_text }}</h1>
        <p style="font-family: papyrus">Posts</p>
    </div>
</div>


<div class='container'> 
        <form action="{% url 'polls:newc' question.id %}" method="post">
        {% csrf_token %}
            <div class="form-group">
                <label for="newc">Express Yourself: </label>
                <input class="form-control" type="textbox" name="newchoice" placeholder="Write Anything!" id="newchoice" pattern=".{5,}" required title="Your post must have at least 5 characters"/>
                </br>
                <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-pencil-alt"></i>  Create New Post</button>
            </div>
        </form>

    <form action="{% url 'polls:index' %}">
        <button type="submit" class="btn btn-info btn-block"><i class="fas fa-home"></i>  Back to Home</button>
    </form>
</div>

</body>

polls/templates/polls/newq.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link href="https://use.fontawesome.com/releases/v5.0.0/css/all.css" rel="stylesheet">
    <title>Name Yourself</title>
</head>

<body style="background-color:powderblue;">

    <div class='container'>
        <div class='jumbotron'>
            <h1 style="font-family:papyrus;">Welcome to Good Forum!</h1>
            <p style="font-family:papyrus;"> Give yourself a name and write about anything you want!</p>
        </div>
    </div>

<div class='container'> 
        <form action="{% url 'polls:newq' %}" method="post">
        {% csrf_token %}
            <div class="form-group">
                <label for="newq">Name Yourself: </label>
                <input class="form-control" type="textbox" name="newquestion" placeholder="Username" id="newquestion" pattern=".{5,}" required title="Your name must have at least 5 characters"/>
                </br>
                <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-user"></i>  Create New User</button>
            </div>
        </form>

    <form action="{% url 'polls:index' %}">
        <button type="submit" class="btn btn-info btn-block"><i class="fas fa-home"></i>  Back to Home</button>
    </form>
</div>

</body>

polls/templates/polls/results.html
<head>
    <title>{{ question.question_text }}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link href="https://use.fontawesome.com/releases/v5.0.0/css/all.css" rel="stylesheet">
</head>

<body style="background-color: powderblue;">

<div class="container">
<div class="jumbotron">    
    
        <h1 style="font-family: papyrus">{{ question.question_text }}</h1>
        <p style="font-family: papyrus">Likes</p>
    </div>
</div>

<div class="container">
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} like{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
</div>


<div class="container">
<form action="{% url 'polls:detail' question.id %}">
<button type="submit" class="btn btn-primary btn-block">Back to Posts</button>
</form>
<form action="{% url 'polls:index' %}">
<button type="submit" class="btn btn-info btn-block"><i class="fas fa-home"></i>  Back to Home</button>
</form>
</div>
</body>